version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  whisper-workflow:
    jobs:
      - code-linters
jobs:
  code-linters:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Prettier
          command: npm run lint:client
      - run:
          name: Prettier
          command: npm run format --workspace=client
