version: 2.1
orbs:
  node: circleci/node@1.1.6

workflows:
  whisper-workflow:
    jobs:
      - build
      - code-linters

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run test
          command: npm test

  code-linters:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Eslint
          command: npm run lint --workspace=client
      - run:
          name: Prettier
          command: npm run format --workspace=client