version: 2.1
orbs:
  node: circleci/node@1.1.6

workflows:
  heroku_deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run test
          command: npm test

  code-linters:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: Eslint
          command: npm run lint --workspace=client
      - run:
          name: Prettier
          command: npm run format --workspace=client